name: "build thesis with nix"
on:
  # pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    - uses: cachix/cachix-action@v15
      with:
        name: anka-213
        # signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    #- run: for f in $(nix-instantiate); do echo $f; cat $f; done
    - run: nix build -L .#document
    - name: Fetch other branch
      run: git fetch origin pre-presentation-fixup:pre-presentation-fixup
    - run: nix develop -L --command sh generate-latex-diff.sh
    # - run: nix-shell --run "echo OK"
